### ISSUE TITLE
README.mdのVSをまとめる

### ISSUE THREAD

**Issue by shu1oka28** [security-anthem/MAID#13]

**Comment by HI-sec-a** [comment]
SpamAssassin ?
https://ja.wikipedia.org/wiki/SpamAssassin

**Comment by HI-sec-a** [comment]
https://www.researchgate.net/publication/344906935_E-MAIL_FORENSICS_TECHNIQUES_AND_TOOLS_FOR_FORENSIC_INVESTIGATION

**Comment by HI-sec-a** [comment]
https://aircconline.com/ijnsa/V12N3/12320ijnsa03.pdf
