### ISSUE TITLE
メールから本文を読み込み，patternと比較する機能の実装

### ISSUE THREAD

**Issue by maplizm** [security-anthem/MAID#15]
patternとは，なりすましの被害にあいやすい商標の名前などで構成される．（ゆう○ょ銀行，ビットコインなど）

**Comment by shu1oka28** [comment]
PRにかかれていた残された課題
現在未完了の項目は，エンコード方式：quoted-printable，文字コード：iso-2022-jpの組み合わせの場合のデコード，メール本文に含まれていたパターンの情報をDBに格納する機能の実装
