### ISSUE TITLE
メールから添付ファイルを読み取り，ハッシュ化する機能の実装

### ISSUE THREAD

**Issue by maplizm** [security-anthem/MAID#16]
出力は添付ファイルのfuzzyハッシュのリスト

**Comment by shu1oka28** [comment]
fuzzyhash関数として，これ使えるかも（MITライセンス）

[https://github.com/cloudtracer/ssdeep.js/](https://github.com/cloudtracer/ssdeep.js/)

gitにsubmoduleの機能があるので使ってもいいと思う

**Comment by shu1oka28** [comment]
#21 により、このissueは完了したためcloseします。
