### ISSUE TITLE
データベース登録部で複数の利用者が同時に利用するときに正しく処理されない可能性がある

### ISSUE THREAD

**Issue by shu1oka28** [security-anthem/MAID#25]
`data_register.py`でm_idの処理方法は以下のようになっている
1. overviewにinsert（通常通りにm_idが増える）
2. receivedにinsertするときに（setval('overview_m_id_seq', currval('overview_m_id_seq'), false),）と記述して、m_idの増加を停止させてm_idをoverviewと結果的に同じ数字が入るようにする
3. attachにinsert（m_idの増加が停止されてる）
4. patternにinsert（insert後にm_idの増加を再開（setval('overview_m_id_seq', currval('overview_m_id_seq'), true)））

**Comment by MMikipenguin** [comment]
同時に利用されるということは，利用者A，Bがinsertしたときに，Aが最初にすべての処理を行ってから
Bがすべての処理を行うわけではないということですか．
Aがoverviewにinsertして1番目のデータとなったときにBが割り込んでoverviewにinsertすると，
Bが2番目のデータとなり，AがBの割り込みから戻ると，残りのinsertは3番目のデータとみなされるということでしょうか．

一つのデータ格納処理が完全に終了するまで，他の処理を待たせると想定していました．
このように他の処理を待たせるという実装はできないもしくは不適切でしょうか．
そうである場合，ご指摘の通りinit.pyでm_idのIDを管理して，
すべての処理が終わった直後にインクリメントする実装に変更します．
（この実装の場合，init.py側で宣言されたm_id変数がdata_register.py側に認識され使えるかがわかりません．）

また，このプログラムでいえば，insertだけを考慮すればよいでしょうか．

よろしくお願いします．

**Comment by shu1oka28** [comment]
> 同時に利用されるということは，利用者A，Bがinsertしたときに，Aが最初にすべての処理を行ってから
Bがすべての処理を行うわけではないということですか．

そのとおりです。同時に複数のプロセスが走って、独立してリクエストを処理する可能性があります。
もし1件ずつ処理するならトランザクション(beginで始めてcommitでおわるやつ)にする必要があります。

今回はoverviewをinsertしたときにm_idを受け取って、
他の3つをinsertするときにm_idを指定することで複数同時処理が実現できそうだと思ってます。

**Comment by MMikipenguin** [comment]
承知しました．

init.pyにm_id変数を1で初期化します．
各テーブルのm_idメンバは，int型に修正します．
data_register.pyでは，各テーブルでstr(m_id変数)でm_idを指定し，処理の最後にm_id変数をインクリメントします．

この実装で問題ないかテストしたいので，「python3 data_register.py & python3 data_register.py」のようにして
実行した結果をみればよいでしょうか．

**Comment by shu1oka28** [comment]
> Serial型では自動的にインクリメントされると思います。

Overviewはm_idを指定せずにinsertして、returningでm_idを受け取れば、postgresqlが自動的につけたm_idがわかると思います。
(勘違いしてたらごめん)

**Comment by shu1oka28** [comment]
> この実装で問題ないかテストしたいので，「python3 data_register.py & python3 data_register.py」のようにして
> 実行した結果をみればよいでしょうか．

そのコマンドでも運がよければ同時に実行できると思う。

本気でテストするならスレッドで同時にやる方法がある。（CTFのWeb問題とかでも使うかも？）
[https://pod.hatenablog.com/entry/2018/09/22/215030](https://pod.hatenablog.com/entry/2018/09/22/215030)

**Comment by MMikipenguin** [comment]
スレッドを使う方法で試します．

m_idを変数で使うということは設計的にグローバル変数になりますが，
init.pyで宣言するとmodule initにm_idはないといわれます．
global_variables.pyを作ってそこにグローバル変数m_idを置いておくのはいかがでしょうか．

**Comment by shu1oka28** [comment]
m_idはpostgresqlが保持する値なので，別にpython側でのグローバル変数はいらないと思います（僕が勘違いしてる？）
data_register.pyでoverviewのinsertで結果を受け取って，あと残り3は普通にm_idを含めてinsertするのが自然な気がします。


```python
cur.execute(
        """
        insert into overview (
          from_header,
          reply_to,
          subject
        )
        
        VALUES (
          %s,
          %s,
          %s
        )
        returning m_id;
        """
        , (
            json_dict['from'],
            json_dict['reply-to'],
            json_dict['subject']
          )
    )
results = cur.fetchall()
m_id=results[0][0]
cur.execute('COMMIT')
```

```python
cur.execute(
          """
          insert into received (
            m_id,
            from_display,
            from_reverse,
            from_ip,
            by,
            protocol,
            ssl,
            spf,
            dkim,
            dmarc
          )
          
          VALUES (
            %s,
            %s,
            %s,
            %s,
            %s,
            %s,
            %s,
            %s,
            %s,
            %s
          );
          """
          , (
              m_id,
              json_rec_from_dict['display'],
              json_rec_from_dict['reverse'],
              json_rec_from_dict['ip'],
              json_rec_dict['by'],
              json_rec_dict['protocol'],
              json_rec_dict['ssl'],
              str(json_rec_dict['spf']),
              str(json_rec_dict['dkim']),
              str(json_rec_dict['dmarc'])
            )
       )
      cur.execute('COMMIT')
```

**Comment by MMikipenguin** [comment]
教えていただいた方法で解決できました．
テストの結果，同時登録でIDなど登録情報や登録自体の成功に影響がないことを確認しました．

ソースコードを確認して，修正したものをプルリクエストします．
ご指摘ありがとうございます．
